# Generated by Django 4.1.3 on 2022-12-02 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("djello", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="card",
            name="order",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="card",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="djello.list",
            ),
        ),
    ]
